defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":9009"

[frontends]
  [frontends.cortex]
    entryPoints = [ "http" ]
    backend = "cortex"
    passHostHeader = true

[backends]
  [backends.cortex]
    [backends.cortex.servers.server1]
      url = "http://cortex1:9009"
      weight = 1
    [backends.cortex.servers.server2]
      url = "http://cortex2:9009"
      weight = 1
    [backends.cortex.servers.server3]
      url = "http://cortex3:9009"
      weight = 1
    [backends.cortex.healthCheck]
      path = "/ring"
      port = 9009
      interval = "10s"
      scheme = "http"