# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 10s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab
    foo:     bar

#remote_write:
#- url: http://cortex-lb/api/prom/push

scrape_configs:
#- job_name: node
#  honor_labels: true
#  static_configs:
#  - targets: ['node-1:9100', 'node-2:9100']

#- job_name: prometheus
#  honor_labels: true
#  static_configs:
#  - targets: ['localhost:9090']

#- job_name: grafana
#  honor_labels: true
#  static_configs:
#  - targets: ['grafana:3000']

- job_name: traefik
  honor_labels: true
  static_configs:
  - targets: ['traefik:80']

#- job_name: cadvisor
#  honor_labels: true
#  scrape_interval: 5s
#  static_configs:
#  - targets: ['cadvisor:8080']
