logLevel = "DEBUG"
defaultEntryPoint = "cortex"

[api]
  dashboard = true

[ping]

[entryPoints]
  [entryPoints.cortex]
    address = ":9009"
  [entryPoints.prom]
    address = ":7007"
  

[file]
  [frontends]
    [frontends.cortex]
      entryPoints = [ "cortex" ]
      backend = "cortex"
      passHostHeader = true

  [backends]
    [backends.cortex]
      [backends.cortex.servers.server1]
        url = "http://cortex1:9009"
        weight = 1
      [backends.cortex.servers.server2]
        url = "http://cortex2:9009"
        weight = 1
      [backends.cortex.servers.server3]
        url = "http://cortex3:9009"
        weight = 1
      [backends.cortex.healthCheck]
        path = "/ring"
        port = 9009
        interval = "10s"
        scheme = "http"

[metrics]
  [metrics.prometheus]
    entryPoint = "prom"
    buckets = [0.1,0.3,1.2,5.0]

